//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finaly
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAS_context : DbContext
    {
        public GAS_context()
            : base("name=GAS_context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<deal_to_card> deal_to_card { get; set; }
        public virtual DbSet<Deals> Deals { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Stations> Stations { get; set; }
    }
}
