//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finaly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deals()
        {
            this.deal_to_card = new HashSet<deal_to_card>();
        }
    
        public int dealID { get; set; }
        public Nullable<int> idofstation { get; set; }
        public Nullable<int> idofproduct { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> totalprice { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> bonus { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deal_to_card> deal_to_card { get; set; }
        public virtual Products Products { get; set; }
        public virtual Stations Stations { get; set; }
    }
}
